# Use root/example as user/password credentials
version: "3"

services:

  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017

  gameserver:
    image: com.chess4you/gameserver
    ports:
      - 8081:8081
    links:
      - mongodb